#!/usr/bin/php

<?php

    if (php_sapi_name() !== 'cli'){
        exit;
    }

    require __DIR__ . '/vendor/autoload.php';

    use Cliwork\App;
    use Cliwork\CommandCall;

    $app = new App;

    $app->setSignature("minicli hello name [ user=name ]");

    //simple command registration
    $app->registerCommand('help', function (array $argv) use ($app) {
        $app->getPrinter()->display("usage: minicli hello [ your-name ]");
    });

    $app->runCommand($argv);
